---
title: "results experiment 2"
output:
  html_document:
    df_print: paged
---

```{r, warning=FALSE, message=FALSE}
library(ggforce)
library(here)
library(tidyverse)
source(here("R", "utils.R"))
source(here("R", "utils-exp2.R"))

N_trials <- list(train=15, test=18, color_vision=8);

# data_dir <-  here("data", "test-runs")
data_dir <- here("data", "prolific")

# result_dir <- here("data", "test-runs", "results", "experiment2")
result_dir <- here("data", "prolific", "results", "experiment2")

fn <- "exp2_tidy.rds"

data <- readRDS(paste(result_dir, fn, sep=.Platform$file.sep))

stimuli <- data$test %>% pull(id) %>% unique()
N_participants <- data$test %>% pull(prolific_id) %>% unique() %>% length()

plot_dir <- paste(result_dir, "plots", sep=.Platform$file.sep);
dir.create(plot_dir, showWarnings = FALSE)
```


## Training data

```{r training}
df <- data$train %>% group_by(prolific_id, id)
```



## Experimental data: Produced sentences
standardized sentences (the green and the blue = the blue and the green, etc.)

```{r}
# summarize utterances
# and / but
df <- data$test %>%
 mutate(across(where(is.factor), as.character),
        response= case_when(str_detect(response, "but") ~
                              str_replace(response, "but", "and"),
                            TRUE ~ response));
s.pos.and = "the blue block and the green block fall"
s.neg.and = "neither the blue block nor the green block fall"
s.pos.if_green = "if the green block falls the blue block falls as well"
s.pos.if_blue = "if the blue block falls the green block falls as well"
s.pos.prob_green = "probably the green block falls"
s.pos.prob_blue = "probably the blue block falls"
s.pos_neg.and_gb = "the green block falls but the blue block does not fall"
s.pos_neg.and_bg = "the blue block falls but the green block does not fall"

dat <- df %>%
  summarize_utts(c("and"), c("does not"), s.pos.and) %>%
  summarize_utts(c("neither"), c("does not"), s.neg.and) %>%
  summarize_utts(c("if the green block"), c("does not"), s.pos.if_green) %>%
  summarize_utts(c("if the blue block"), c("does not"), s.pos.if_blue) %>%
  summarize_utts(c("the green block probably"), c("does not"), s.pos.prob_green) %>%
  summarize_utts(c("the blue block probably"), c("does not"), s.pos.prob_blue) %>%
  summarize_utts(c("and", "the green block falls", "the blue block does not"), c(),
                 s.pos_neg.and_gb) %>%
  summarize_utts(c("and", "the blue block falls", "the green block does not"), c(),
                 s.pos_neg.and_bg)

dat %>% 
  select(response) %>% unique()
```

```{r all-trials}
plotTrials <- function(dat, n_pages, trials="all", min=0){
  ids = dat$id %>% unique()
  n = ids %>% length();
  brks=seq(0, 1, by=0.1)
  
  dat <- dat %>%
    mutate(response = as.factor(response)) %>%
    group_by(id,response) %>%
    summarize(n=n(), .groups='drop_last') %>%
    mutate(N=sum(n), ratio=n/N) %>% 
    filter(ratio>min)
      
  if(trials=="all"){
    for(i in seq(1, n)) {
      df <- dat %>% filter(id == ids[[i]]) %>% 
        mutate(response=fct_reorder(response, desc(-ratio)))
      p <- df %>% filter(id == ids[[i]]) %>% 
        ggplot(aes(x=ratio, y=response)) +
        geom_bar(stat="identity") +
        theme(text = element_text(size=20),
              axis.text.x=element_text(angle=45, vjust = 0.5)) +
        labs(x="percentage of participants who built utterance", y="built utterance", title = ids[[i]]) +
        theme_bw()
      print(p)
    }
  } else {
    p <- dat %>%
      filter(str_detect(id, trials)) %>%
      mutate(response=fct_reorder(response, desc(-ratio))) %>% 
      ggplot(aes(x=ratio, y=response)) +
      geom_bar(aes(fill=id), stat="identity", position=position_dodge(preserve="single")) +
      theme_bw() +
      theme(text = element_text(size=20),
            axis.text.x=element_text(angle=45, vjust = 0.5),
            legend.position="bottom") +
      labs(x="percentage of participants who built utterance", y="built utterance")
    print(p)
  }
}
```

Plot responses per trial

```{r}
dat %>% group_by(id) %>% plotTrials(N_trials$test/2 + 1)
```

All trials 

```{r}
dat$id %>% unique()
```


```{r, fig.width=15}
# +1 for example test-trial (ind2)
dat %>% group_by(id) %>% plotTrials(N_trials$test/2 + 1, trials = "if1_hh|independent_hh", 0.15)
dat %>% group_by(id) %>%
  plotTrials(N_trials$test/2 + 1,
             trials = "if1_uh|if1_u-Lh|if1_u-Hh|if2_ul|if2_u-Ll|if2_u-Hl|independent_uh", 0.15)
dat %>% group_by(id) %>%
  plotTrials(N_trials$test/2 + 1,
             trials = "if1_lh|if1_uh|if1_u-Lh|if1_u-Hh|if1_hh|if2_ul|if2_u-Hl|if2_u-Ll", 0.15)

```

Plot custom responses

```{r,  fig.height = 5, fig.width = 10}
dat.custom = dat %>% filter(!is.na(custom_response)) %>% group_by(id)
dat.custom %>%
  ggplot(aes(x=fct_rev(fct_infreq(custom_response)))) + geom_bar(aes(fill=id)) +
  theme(text = element_text(size=20),
        axis.text.x=element_text(angle=45, vjust = 0.5)) +
  labs(y="#participants") +
  coord_flip() +
  theme_bw()
```

Plot specific trials seperately
```{r}
trial = "independent_ll"
data.specific = dat %>% filter(id==trial) %>% group_by(id)
data.specific %>%
  ggplot(aes(x=fct_rev(fct_infreq(response)))) + geom_bar() +
  facet_wrap(~group) +  
  theme(text = element_text(size=14),
        axis.text.x=element_text(angle=45, vjust = 0.5)) +
  labs(y="#participants", x="response", title=trial) +
  coord_flip() +
  theme_bw()
```

Plot set of generated utterances

```{r all-sentences,  fig.height = 7, fig.width = 15}
plotSentences <- function(dat){ 
  df.sum = dat %>% group_by(response) %>% summarize(N=n(), .groups="keep")
  max <- df.sum %>% ungroup() %>% select(N) %>% max()
  p <- dat %>% 
    ggplot(aes(y=fct_rev(fct_infreq(response)))) +
    geom_bar(aes(fill=id), stat="count") + #   hier weiter machen!
    theme_bw() +
    labs(x="times generated", y="response", fill="trial id") +
    theme(text = element_text(size=20), legend.position = "top") 
    # scale_x_discrete(name="# generations", breaks = seq(1, max, by=20), labels = sprintf("%s", breaks), limits=sprintf("%s", breaks))
  return(p)
}
p <- dat %>% plotSentences()
p
```





```{r}
data$comments
```


