---
title: "stats Experiment 1"
output:
  html_document:
    df_print: paged
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(here)
library(tidyverse)
source(here("R", "utils.R"))

# result_dir <-  here("data", "test-runs");
result_dir <- here("data", "prolific", "results", "experiment1")
data_fn <- "exp1_tidy.rds"
path_data <- paste(result_dir, data_fn, sep=.Platform$file.sep)

data <- readRDS(path_data)
```

## Duration

```{r}
df <- data$info %>% group_by(prolific_id) %>% distinct()

p <- df %>%
  ggplot(aes(x=factor(0), y=timeSpent)) + geom_boxplot() + 
  geom_jitter(shape=16) +
  geom_hline(aes(yintercept = mean(df$timeSpent) + sd(df$timeSpent),
                 color="yellow")) +
  geom_hline(aes(yintercept = mean(df$timeSpent) + 2 * sd(df$timeSpent),
                 color="red")) +
  theme(legend.position="none") + 
  labs(x = "", y="timeSpent in min.")
p

df %>% ungroup() %>%  group_by(prolific_id) %>%  summary()
```


```{r, include=FALSE, eval=FALSE}
## Train Trials Color Vision

df <- data$color %>% group_by(prolific_id, id) %>%
  mutate(correct = expected == response)

df %>%
  ggplot(aes(x=id)) + geom_bar(position="dodge", aes(fill=correct)) +
  theme(axis.text.x = element_text(angle=90, hjust=1), legend.position = "top")

```

## Train Trials

```{r}
df <- data$train %>% group_by(prolific_id, id)
df.slider <- df %>% filter(trial_name == "animation_slider") 
df.buttons_correct = df %>%
  filter(case_when(expected == "response1" ~ icon_idx == 1,
                   expected == "response2" ~ icon_idx == 2, 
                   expected == "response3" ~ icon_idx == 3,
                   expected == "response4" ~ icon_idx == 4, 
                   ))
# not everyone saw the same trial as slider - trial, therefore sums will not 
# always be exactly the number of participants.
df.buttons_correct %>%
  ggplot(aes(x=id)) + geom_bar(position="dodge", aes(fill=response)) + 
  theme(axis.text.x=element_text(angle=90, hjust=1), legend.position = "top") + 
  guides(fill = guide_legend(title = "correct"))


```


## Reaction times (per experimental trial)

```{r}
df <- data$test %>% select(prolific_id, id, RT) %>% group_by(id) %>% distinct()

# TODO: points are added twice?
RT_mu = mean(df$RT)
p <- df %>%  ggplot(aes(x=id, y=RT)) + geom_boxplot() +
  geom_hline(aes(yintercept = RT_mu), color="green", linetype="dashed") +
  geom_hline(aes(yintercept = RT_mu + sd(df$RT)), color="orange") +
  geom_hline(aes(yintercept = RT_mu + 2 * sd(df$RT)), color="red") +
  theme(legend.position="none", axis.text.x = element_text(angle=90)) +
  ggtitle("Reaction times per test stimulus")  
p
```

General comments

```{r}
data$comments
data$comments$comments
data$comments$noticed_steepness
```

# Postprocessing
##Filter out participants who did not notice different degrees of inclines

```{r}
filter_prolific_id <- function(df){
  df <- df %>%
    filter(prolific_id != "participant2" & prolific_id != "participant3" &
           prolific_id != "participant11" & prolific_id != "participant13" &
           prolific_id != "participant14")
  print(paste('# filtered out because of not noticing steepness:', "5"))
  return(df)
}

update_data <- function(result_dir){
  target_fn <-"exp1_test_trials_processed.rds";
  target_path <- paste(result_dir, target_fn, sep=.Platform$file.sep);
  df <- readRDS(target_path) %>% filter_prolific_id();
  saveRDS(df, paste(result_dir,
    "exp1_test_trials_processed_steepness_noticed.rds", sep=.Platform$file.sep))
  
  # also update (mean) tables
  tables.all <- df %>% select(id, question, prolific_id, response) %>%
    group_by(id, question, prolific_id) %>%
    pivot_wider(names_from = question, values_from = response)
  write.table(tables.all, file=paste(result_dir,
    "exp1_prob_tables_all_steepness_noticed.csv", sep=.Platform$file.sep),
    sep = ",", row.names=FALSE)
  
  means <- df %>% group_by(id, question) %>% summarise(mean=mean(response))
  write.table(means %>% pivot_wider(names_from = question, values_from = mean),
              file=paste(result_dir, "exp1_prob_tables_mean_steepness_noticed.csv", sep=.Platform$file.sep),
              sep = ",", row.names=FALSE)
}

update_data(result_dir);
```

